sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update 
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-latex-extra
- sudo apt-get install texlive-bibtex-extra biber latex-xcolor

#before_script:
    # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
    # - wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
    #- wget "http://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/0.9.9/binaries/Linux/biber-linux_x86_64.tar.gz"
    #- tar xzf biber-linux_x86_64.tar.gz
    #- export PATH=$PATH:$PWD
    
script:
    - cd paper
    - pdflatex -interaction=nonstopmode RFPPC2019_Hillairet.tex
    - bibtex RFPPC2019_Hillairet
    - pdflatex -interaction=nonstopmode RFPPC2019_Hillairet.tex
    - pdflatex -interaction=nonstopmode RFPPC2019_Hillairet.tex

deploy:
  provider: releases
  api_key:
    secure: JJxinuqYrHySqN+zePYquu/j+T5LtJRoKDPH7mF5LAtH+LX7nMXWIwe2q8Fz1OW0+U5BkMpKw1EFZMrTG/H34hY90O7vLLqBA8APkgiDpW3xEoOEiYDohbjAd2SmnoSo4BFgz5/UrDAW2n+AM0yEtv86XEPKdZJQypEN65sAntcEbBKX1E2mBsinZb0Ct3gXzKqQzz0eEq5Qjn3tudrX9FBa40nBsOUeAeHIVoPyGG+X7cwye40gev513MNra0dYEBUSUxX3KmxaPHjYoTiy1fYHagMEmiQdW9OmCrd5DDRaTMJosqqgARUdof1xNrxn7A9Pb6roW2NF8q82zVuNJBjkzSiNFFgu0gcebSh5xG32+l86Tpo7V9UhafFX2qWayBj4ZKdxEQCoLN6SOOqY/13P8nJ4iP8AurTmMBXFb+jp5TVlaOMpILsqFdEvySFtO1p61nx3ClSrF4fegDjwIKvxls1rGlwwmMD0MVy76O1mvqkGnfTqCIaZ9Ych8EibrTM6/vatxigU112paq/WjSI6/jtpAveKGYptWGVG/DmqHAHoKEFthZb2q2m1zGUuQYP77mbrIsWO6HnwcBWUvMOTy4Ei4HxdzLnTfIVUURZJgdKIFIo6jcrdCHUmlyfJUbEqxUZgt1xc4YursqdOpctQWD/JxeCXjDL6nXlJeUQ=
  file: RFPPPC2019_Hillairet.pdf
  skip_cleanup: true
  on:
    repo: jhillairet/RFPPC2019
